spring.application.name=simple-ewallet-system
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:ewalletdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=b7e4a92f6c81d35e9047af1c9d62d4e9153f7a2c8b41d6e9057af3c8b62d4e9
jwt.expiration = 86400000